name: OR-design-flow

on: [pull_request, workflow_dispatch ]

jobs:
  publish-mock-data:
    
    name: publish mock data
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload GRT artifact
        uses: actions/upload-artifact@v4
        with:
          name: PD-grt-L1MetadataArray-base
          path: .github/scripts/dashboard_physical-design/L1MetadataArray/base/5_1_grt.json
      


